compose.yml
compose/asb.json

We will need to send and receive messages from the ASB locally when testing and developing.
This adds the services to the docker-compose file.  The other bits have just been commented out for later use.

Feature: Add docker services for ASB

---

src/Processor/Program.cs

This was missing but the IWebProxy is only required when running in CDP.

Register the web proxy in the DI

---

.github/workflows/publish.yml

The pipeline is currently failing.  I think this may give the sub-workflow permission to read the packages.

CDMS-487: Add packages: read permission to the publish workflow

---

src/Processor/Consumers/NotificationConsumer.cs
src/Processor/Models/ImportNotification/Mappers/ImportNotificationMapper.cs
src/Processor/Models/ImportNotification/Mappers/ImportNotificationWithTransformMapper.cs
src/Processor/Processor.csproj
tests/Directory.Build.targets
tests/Processor.IntegrationTests/Consumers/NotificationConsumerTests.cs
tests/Processor.Tests/Consumers/NotificationConsumerTests.cs
tests/TestFixtures/ImportNotificationFixtures.cs
tests/TestFixtures/TestFixtures.csproj

Pull in changes from 0.3.0 pre release from PR https://github.com/DEFRA/trade-imports-data-api/pull/35.
Further work on the above PR is needed as endpoint paths have also changed.
Also fixed a package security warning. This might not have triggered in the pipeline as it was for a testing dependency and not related to code that would have made it into the final Docker image.

Update to pre release 0.3.0 of data API

---

tests/Processor.Tests/Consumers/NotificationConsumerTests.cs
tests/TestFixtures/ImportNotificationFixtures.cs

A bit of a redundant test but it covers off the functionality of the old system.

CDMS-134: Add test to ensure cancelled or deleted notifications are sent to the Data API

---

src/Processor/Consumers/CustomsDeclarationsConsumer.cs
tests/Processor.Tests/Consumers/CustomsDeclarationsConsumerTests.cs
tests/TestFixtures/ClearanceRequestFixtures.cs

We don't want to save ClearanceRequests that come through when there is a newer version stored within the Data Api.

CDMS-135: Discard old ClearanceRequests

---

.github/dependabot.yml

Configure dependabot to use classic PAT (as this is all it supports when private nuget repos are being used)

---

src/Processor/Consumers/CustomsDeclarationsConsumer.cs
tests/Processor.Tests/Consumers/CustomsDeclarationsConsumerTests.cs
tests/TestFixtures/FinalisationFixtures.cs

We have decided to use the `EntryVersionNumber` to establish whether a Finalisation message is later than the existing record, which is what the Clearance Requests does.

CDMS-478: Only persist the Finalisation message if it is a later version

---

src/Processor/Consumers/CustomsDeclarationsConsumer.cs
src/Processor/Models/CustomsDeclarations/InboundError.cs
src/Processor/Models/CustomsDeclarations/InboundErrorItem.cs
src/Processor/Models/CustomsDeclarations/InboundHmrcMessageType.cs
tests/Processor.Tests/Consumers/CustomsDeclarationsConsumerTests.cs
tests/TestFixtures/InboundErrorFixtures.cs

This takes any messages from gateway with the InboundError message type error and discards them until the Data Api is ready to receive them.

CDMS-481: Receive InboundErrors from the gateway

---

tests/Processor.IntegrationTests/Consumers/CustomsDeclarationsConsumerTests.cs

This adds an integration test for Inbound Errors to simulate pulling an error from the queue, processing it and then saving it via the Data Api.

CDMS-483: Add integration test for Inbound Errors

---

.github/workflows/check-pull-request.yml
src/Processor/Consumers/CustomsDeclarationsConsumer.cs
src/Processor/Extensions/ServiceCollectionExtensions.cs
src/Processor/Validation/CustomsDeclarations/ClearanceRequestValidator.cs
src/Processor/Validation/CustomsDeclarations/FinalisationValidator.cs
tests/Processor.IntegrationTests/Consumers/CustomsDeclarationsConsumerTests.cs
tests/Processor.Tests/Consumers/CustomsDeclarationsConsumerTests.cs
tests/Processor.Tests/Validation/CustomsDeclarations/ClearanceRequestValidatorTests.cs
tests/TestFixtures/ClearanceRequestFixtures.cs
tests/TestFixtures/FinalisationFixtures.cs
tests/TestFixtures/InboundErrorFixtures.cs

This enables the validation with the currently implemented validators. At the moment it will just skip the message, which is the intended behaviour, but only logs the errors out and does not send them onwards.
The fixture generation functions required some more explicit configuration to ensure that they were valid for the rules.
A couple of fixes were identified for the validation rules which have been updated.

CDMS-476: Enable validation on ClearanceRequest, Finalisation and ServiceHeaders

---

Makefile
compose.yml
compose/asb.json
src/Processor/Consumers/CustomsDeclarationsConsumer.cs
src/Processor/Extensions/ServiceCollectionExtensions.cs
src/Processor/Models/CustomsDeclarations/Header.cs
src/Processor/Models/CustomsDeclarations/ServiceHeader.cs
src/Processor/Validation/CustomsDeclarations/CheckValidator.cs
src/Processor/Validation/CustomsDeclarations/ClearanceRequestValidator.cs
src/Processor/Validation/CustomsDeclarations/ClearanceRequestValidatorInput.cs
src/Processor/Validation/CustomsDeclarations/CommodityValidator.cs
src/Processor/Validation/CustomsDeclarations/CustomsDeclarationsMessageValidator.cs
src/Processor/Validation/CustomsDeclarations/FinalisationValidator.cs
src/Processor/Validation/CustomsDeclarations/HeaderValidator.cs
src/Processor/Validation/CustomsDeclarations/HeaderValidatorInput.cs
src/Processor/Validation/CustomsDeclarations/ImportDocumentValidator.cs
tests/Processor.IntegrationTests/Consumers/CustomsDeclarationsConsumerTests.cs
tests/Processor.IntegrationTests/Helpers/AsyncWaiter.cs
tests/Processor.Tests/Consumers/CustomsDeclarationsConsumerTests.cs
tests/Processor.Tests/Validation/CustomsDeclarations/CheckValidatorTests.cs
tests/Processor.Tests/Validation/CustomsDeclarations/ClearanceRequestValidatorTests.cs
tests/Processor.Tests/Validation/CustomsDeclarations/CommodityValidatorTests.cs
tests/Processor.Tests/Validation/CustomsDeclarations/CustomsDeclarationsMessageValidatorTests.cs
tests/Processor.Tests/Validation/CustomsDeclarations/ExpectedResult.cs
tests/Processor.Tests/Validation/CustomsDeclarations/FinalisationValidatorTests.cs
tests/Processor.Tests/Validation/CustomsDeclarations/ImportDocumentValidatorTests.cs
tests/TestFixtures/ClearanceRequestFixtures.cs

This adds some missing validation checks which are not ALVSVAL* errors.
These checks should log the message but not send it to the Data Api.
The existing tests have been reorganised around the type they are testing to avoid the nested assertions.

CDMS-476: Add more validation checks and reorganises existing ones

---

src/Processor/Consumers/CustomsDeclarationsConsumer.cs
src/Processor/Processor.csproj
tests/Processor.Tests/Consumers/CustomsDeclarationsConsumerTests.cs

It will be useful to record the message body and the time of creation when reporting ALVSVAL errors to more quickly follow up on them.
We only store the latest version of each record so any versions that failed validation would be discarded.

CDMS-476: Send message body and created time during ALVSVAL error reporting

---

src/Processor/Models/CustomsDeclarations/InboundError.cs
tests/Processor.Tests/Models/InboundErrorTests.InboundError_ConversionToDataApiInboundError_IsCorrect.verified.txt

The `Created` field was unused for Inbound Errors, so we may as well set it to the time that CDS sent the message to us.

CDMS-487: Set the Created field to the ServiceCallTimestamp for Inbound Errors

---

src/Processor/Consumers/CustomsDeclarationsConsumer.cs
src/Processor/Extensions/ServiceCollectionExtensions.cs
src/Processor/Validation/CustomsDeclarations/ErrorNotificationValidator.cs
src/Processor/Validation/CustomsDeclarations/FinalisationValidator.cs
tests/Processor.Tests/Consumers/CustomsDeclarationsConsumerTests.cs
tests/Processor.Tests/Validation/CustomsDeclarations/ErrorNotificationValidatorTests.cs
tests/TestFixtures/InboundErrorFixtures.cs

This adds in a validator for Inbound Error notifications, checking the codes on the errors to be ones that we are aware of.
If a notification has any unknown codes we log and skip it.

CDMS-484: Validate Inbound Error notification messages

---

src/Processor/Models/Gmrs/Gmr.cs
src/Processor/Models/Gmrs/GmrActualCrossing.cs
src/Processor/Models/Gmrs/GmrCheckedInCrossing.cs
src/Processor/Models/Gmrs/GmrDeclaration.cs
src/Processor/Models/Gmrs/GmrDeclarations.cs
src/Processor/Models/Gmrs/GmrPlannedCrossing.cs
tests/Processor.Tests/Models/DataApi.Gmr_DeserializesCorrectly.verified.txt
tests/Processor.Tests/Models/GmrTests.Gmr_DeserializesCorrectly.verified.txt
tests/Processor.Tests/Models/GmrTests.cs

This was taken from the legacy system but apparently did not actually work.

CDMS-488: Remove JsonPropertyNames from the Gmr model

---

src/Processor/Consumers/ImportNotificationStatus.cs
src/Processor/Consumers/NotificationConsumer.cs
tests/Processor.Tests/Consumers/NotificationConsumerTests.cs

The current logic for determining whether to update a notification is confusing and doesn't work correctly.
This adds a priority to each status which BTMS is interested in and uses that instead.

BAU: Add priority for each Ipaffs notification status

---

src/Processor/Extensions/ServiceCollectionExtensions.cs

logging interceptor needs to happen after the trace interceptor because that is what sets up the trace id

change order of interceptors being registered

---

src/Processor/Extensions/DataApiCustomsDeclarationFinalisationExtensions.cs
src/Processor/Models/CustomsDeclarations/FinalStateValues.cs
src/Processor/Models/CustomsDeclarations/Finalisation.cs
src/Processor/Processor.csproj
src/Processor/Validation/CustomsDeclarations/ClearanceRequestValidator.cs
src/Processor/Validation/CustomsDeclarations/FinalisationValidator.cs
tests/Processor.IntegrationTests/Consumers/CustomsDeclarationsConsumerTests.cs
tests/Processor.Tests/Models/FinalisationTests.Finalisation_ConversionToDataApiFinalisation_IsCorrect.verified.txt
tests/Processor.Tests/Validation/CustomsDeclarations/ClearanceRequestValidatorTests.cs
tests/Processor.Tests/Validation/CustomsDeclarations/FinalisationValidatorTests.cs

The Data Api is now expecting a string for the FinalState.

CDMS-655: Send FinalState as a string to match the Data Api spec

---

src/Processor/Processor.csproj
src/Processor/Validation/CustomsDeclarations/CheckValidator.cs
src/Processor/Validation/CustomsDeclarations/ClearanceRequestValidator.cs
src/Processor/Validation/CustomsDeclarations/CommodityValidator.cs
src/Processor/Validation/CustomsDeclarations/ErrorNotificationValidator.cs
src/Processor/Validation/CustomsDeclarations/FinalisationValidator.cs
src/Processor/Validation/CustomsDeclarations/HeaderValidator.cs
src/Processor/Validation/CustomsDeclarations/ImportDocumentValidator.cs
src/Processor/Validation/CustomsDeclarations/ServiceHeaderValidator.cs
tests/Processor.Tests/Validation/CustomsDeclarations/ClearanceRequestValidatorTests.cs
tests/Processor.Tests/Validation/CustomsDeclarations/HeaderValidatorTests.cs

This adds the ticket numbers to the validation rules to more easily find them in Jira.
One of the rules was a duplicate which would not have been triggered, so has been removed.
The validation rules have been changed to be closer to what btms-backend had, but the tests have not been changed.

CDMS-689: Add ticket numbers to validation rules, tweak rules

---

src/Processor/Consumers/CustomsDeclarationsConsumer.cs
src/Processor/Consumers/GmrsConsumer.cs

It is useful to see in the logs which ALVS error code has been triggered, if present.

CDMS-689: Log the ALVS error code if present

---

src/Processor/Validation/CustomsDeclarations/CommodityValidator.cs
tests/Processor.Tests/Validation/CustomsDeclarations/CommodityValidatorTests.cs

The IUU Check Code H224 is usually specified alongside H222, which causes ALVSVAL317 to trigger because we only allow one check per authority.
IUU Check Codes should be excluded from this rule and the validation should only run on the remaining check codes.

CDMS-698: Exclude IUU Check Codes from ALVSVAL317

---

src/Processor/Validation/CustomsDeclarations/CommodityValidator.cs
tests/Processor.Tests/Validation/CustomsDeclarations/CommodityValidatorTests.cs

GMS Notifications with a CheckCode of H220 do not need a document to be specified and should not trigger ALVSVAL318.

CDMS-699: Exclude GMS Notifications from ALVSVAL318

---

src/Processor/Validation/CustomsDeclarations/CommodityValidator.cs
tests/Processor.Tests/Validation/CustomsDeclarations/CommodityValidatorTests.cs

When a GMS check code is specified, it does not require an associated document to be specified along side it.
This removes any GMS check codes from being validated for ALVSVAL321.

CDMS-700: Exclude GMS check codes from ALVSVAL321

---

src/Processor/Validation/CustomsDeclarations/FinalisationValidator.cs
tests/Processor.Tests/Validation/CustomsDeclarations/FinalisationValidatorTests.cs

We now understand that cancelled messages is not relevant for this validation check.

CDMS-701: Re-enable ALSVAL401 with updated logic

---

src/Processor/Validation/CustomsDeclarations/CommodityValidator.cs
tests/Processor.Tests/Validation/CustomsDeclarations/CommodityValidatorTests.cs

We shouldn't be validating that no documents have been passed.

CDMS-704: Remove ALVSVAL308 check for no documents

---

src/Processor/Validation/CustomsDeclarations/CommodityValidator.cs
tests/Processor.Tests/Validation/CustomsDeclarations/CommodityValidatorTests.cs

The check codes are for different departments within the same umbrella, so duplicate check codes are acceptable.

CDMS-703: Update department names for the DocumentCode/CheckCode map

---

src/Processor/Validation/CustomsDeclarations/CommodityValidator.cs
src/Processor/Validation/CustomsDeclarations/CustomsDeclarationMappings.cs
src/Processor/Validation/CustomsDeclarations/ImportDocumentValidator.cs
tests/Processor.Tests/Validation/CustomsDeclarations/ImportDocumentValidatorTests.cs
tests/TestFixtures/ClearanceRequestFixtures.cs

We were missing this document from the list.
This change consolidates the two lists of documents taken from btms-backend, which results in C633 being removed because it does not have an authority mapping. This has been raised and we will follow up.

CDMS-716: Add N852 to allowed documents

---

src/Processor/appsettings.cdp.dev.json
src/Processor/appsettings.json

Previously this was just set in DEV but we will most likely not revisit this setting and it's important in relation to other services consuming at 20 instances per host.
Therefore, set this for all environments now as our baseline.

Set 10 consumers per host across all environments

---

src/Processor/Authentication/BasicAuthenticationHandler.cs

This PR stops the following log message from being written when a /health request is being processed, which allows anonymous access:
```
"Basic" was not authenticated. Failure message: "Failed authorization"
```

Don't execute the auth if it's running for an endpoint that allows anonymous

---

src/Processor/Utils/Logging/WebApplicationBuilderExtensions.cs

Our health check calls generate continual noise once deployed. However, we don't want to get rid of the them entirely.
This PR filters logs so we only get the following:
```
Request finished "HTTP/1.1" "GET" "http"://"localhost:8080""""/health""" - 200 null "application/json; charset=utf-8" 9.5113ms
```
Alongside any non Information logs ie errors, warnings etc related to health endpoint execution.

Silence volume of logs related to health endpoint calls

---

src/Processor/Extensions/ServiceCollectionExtensions.cs

The standard resilience handler includes two strategies we do not want by default.
A rate limiter - this protects downstream services and we do not have a rate limit currently for the data API, therefore we are removing.
A circuit breaker - similar to the above, we have no established SLA therefore a circuit breaker can introduce more harm than good when it's used unknowingly as the data API may return enough errors to open the circuit, which will prevent traffic from being sent from the processor to the data API; when in reality the data API could recover sooner than the circuit breaker allows. Therefore, for now, we are removing the circuit breaker.
I am also enabled Jitter for the retry policy as it's not a default.
All other settings are provided as defaults from the …

Remove rate limiter and circuit breaker from data API resilience pipeline

---

src/Processor/Models/CustomsDeclarations/ClearanceRequest.cs
tests/Processor.IntegrationTests/Consumers/CustomsDeclarationsConsumerTests.cs
tests/Processor.IntegrationTests/Helpers/ExcludePropertyJsonConverter.cs

We saw a deserialisation error:
```
System.Text.Json.JsonException: JSON deserialization for type 'Defra.TradeImportsProcessor.Processor.Models.CustomsDeclarations.ClearanceRequest' was missing required properties including: 'items'.
at void System.Text.Json.ThrowHelper.ThrowJsonException_JsonRequiredPropertyMissing(JsonTypeInfo parent, BitArray requiredPropertiesSet)
at bool System.Text.Json.Serialization.Converters.ObjectDefaultConverter<T>.OnTryRead(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options, ref ReadStack state, out T value)
at bool System.Text.Json.Serialization.JsonConverter<T>.TryRead(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options, ref ReadStack state, out T value, out bool isPopulatedValue)
at bool …
```

Change Items so it's not a required field and will deserialise as an empty array

---

Defra.TradeImportsProcessor.sln.DotSettings
src/Processor/Endpoints/EndpointRouteBuilderExtensions.cs
src/Processor/Extensions/ServiceCollectionExtensions.cs
tests/Processor.IntegrationTests/Endpoints/ReplayClearanceRequestsEndpointTests.cs
tests/Processor.IntegrationTests/Endpoints/ReplayFinalisationsEndpointTests.cs
tests/Processor.IntegrationTests/Endpoints/ReplayImportPreNotificationEndpointTests.cs

We're now sending clearance requests and finalisations from the message replay service directly, as we want to isolate the gateway and not affect it with unnecessary replay traffic when it's live. 
The gateway is also configured not to send traffic to the BTMS stack so we couldn't use it anyway without deploying a new version and our downstream services might not be in full service.
Consumers are transient so they're new instances on each request. 
The endpoint then sets the context on each new consumer with a fake message ID.

Add replay endpoints for customs declarations and finalisations

---

src/Processor/Consumers/AzureConsumerErrorHandler.cs
src/Processor/Utils/Logging/WebApplicationBuilderExtensions.cs
tests/Processor.Tests/Consumers/AzureConsumerErrorHandlerTests.cs

Added a warning log so we can see dead lettering by trace ID.
Removed SMB error log about the same as it's already logged in our logging interceptor.

Logging follow up PR after testing in DEV

---

src/Processor/Configuration/CustomsDeclarationsConsumerOptions.cs
src/Processor/Configuration/ServiceBusOptions.cs
src/Processor/Extensions/ServiceCollectionExtensions.cs
src/Processor/appsettings.cdp.prod.json
src/Processor/appsettings.json
tests/Processor.Tests/Consumers/AzureConsumerErrorHandlerTests.cs

To prevent SQS / Azure service bus message consumption from automatically starting.
The services can be deployed to any given environment and then message consumption can be switched on once the initial due diligence has taken place

CDMS-554 - Add AutoStartConsumers option to config

---

src/Processor/Consumers/AzureConsumerErrorHandler.cs
src/Processor/Extensions/ServiceCollectionExtensions.cs
src/Processor/Metrics/AzureDeadLetterBackgroundService.cs
src/Processor/Metrics/AzureMetrics.cs
src/Processor/Metrics/ConsumerMetrics.cs
src/Processor/Metrics/IConsumerMetrics.cs
src/Processor/Metrics/RequestMetrics.cs
src/Processor/Program.cs
src/Processor/Utils/Http/Proxy.cs
tests/Processor.Tests/Consumers/AzureConsumerErrorHandlerTests.cs

Potentially controversial - this proposal allows the dead letter queue count from Azure for the two topics we consumer (notifications and GMRs) to be peeked, which are then written as a metric in AWS.
We were doing these previously when consumption from Azure resulted in a dead letter scenario. But we were incrementing a metric so if the DLQ was emptied, our metric would still be incrementing.
With this change, the metric we visualise and alert on will be tracking the actual number of messages on the DLQ at a point in time.
Obviously, this polling logic will run in however many hosts of the processor are deployed. There is a startup delay for each host that will ensure the polling starts between 30 and 120 seconds from host instantiation. The wait period between poll cycles is 5 minutes. …

Track the DLQ count for each Azure topic by peeking the messages

---

src/Processor/appsettings.cdp.dev.json

Reverts DEFRA/trade-imports-processor#166
This is causing startup failure in DEV as the connection string secret has already been changed.

Revert "CDMS-653: Temporarily refer to IPAFFS TST azure topic subscription"

---

src/Processor/appsettings.cdp.prod.json

The main appsettings.json sets `AutoStartConsumers` to `true`, therefore config can be removed in the prod appsettings.json so we accept the default value.

Turn on GMR consumption in prod

---

src/Processor/Consumers/GmrsConsumer.cs
tests/Processor.Tests/Consumers/GmrConsumerTests.cs
tests/TestFixtures/GmrFixtures.cs

We see write errors when a GMR already exists, therefore we are processing updates as well as inserts.
This PR updates the consumer so it can determine if it needs to save the GMR. It uses the `UpdatedDateTime` of the GMR to determine if what is stored is the latest update for us to store.
This logic is equivalent to what happens for IPAFFS.

Allow GMR to be updated if it already exists

---

src/Processor/Consumers/ImportNotificationStatus.cs
src/Processor/Consumers/NotificationConsumer.cs
tests/Processor.Tests/Consumers/NotificationConsumerTests.cs

We want to skip AMEND, DRAFT and MODIFY Ipaffs statuses because they are states that we are not currently concerned about.

CDMS-962: Add Modify, then skip it with improved logging

---

src/Processor/Health/AsbHealthCheckBuilderExtensions.cs
src/Processor/Health/ServiceCollectionExtensions.cs
src/Processor/Services/ClearanceRequestStrategy.cs
src/Processor/Services/DecisionNotificationStrategy.cs
src/Processor/Services/FinalisationStrategy.cs
src/Processor/Utils/Http/Proxy.cs
tests/Processor.IntegrationTests/Health/HealthTests.cs

Ahead of the processor being in cutover mode, this PR will add a health check to allow us to see that we can connect to the alvs_topic in prod.

Add topic health check for alvs_topic

---

src/Processor/Configuration/BtmsOptions.cs
src/Processor/Extensions/ServiceCollectionExtensions.cs
src/Processor/appsettings.cdp.perf-test.json

In perf test we don't want to publish to anything real but we do want to consume.

Allow publishing to IPAFFS to be disabled and disable it in perf test
