src/Processor/appsettings.cdp.dev.json

This adds the config to development for the new ASB topic and subscription.

Add development topic/subscription config

---

src/Processor/Configuration/CdpOptions.cs
src/Processor/Program.cs
src/Processor/Utils/Http/Proxy.cs
tests/Processor.Tests/Utils/ProxyTests.cs

The proxy environment variable was not being picked up because it wasn't being added to the DI properly.

Correct proxy configuration

---

.github/dependabot.yml

Second attempt for dependabot and the Defra nuget feed.

Try adding all * for registries to use

---

src/Processor/Processor.csproj

As per PR title. Bump to pre release of 0.6.0

Update to latest data API client

---

tests/Processor.IntegrationTests/Consumers/CustomsDeclarationsConsumerTests.cs

Updated the integration test to check that the Customs Declaration was sent to the Data Api.

CDMS-475: Update Customs Declarations integration test

---

src/Processor/Models/CustomsDeclarations/ClearanceRequest.cs
tests/Processor.Tests/Models/ClearanceRequestTests.ClearanceRequest_ConversionToDataApiClearanceRequest_IsCorrect.verified.txt

The clearance request checks should also be passed to the API.

CDMS-473: Add the checks to the API request

---

src/Processor/Consumers/CustomsDeclarationsConsumer.cs
src/Processor/Consumers/NotificationConsumer.cs
src/Processor/Models/CustomsDeclarations/Finalisation.cs
src/Processor/Models/CustomsDeclarations/Header.cs
tests/Processor.IntegrationTests/Clients/WireMockClient.cs
tests/Processor.IntegrationTests/Consumers/CustomsDeclarationsConsumerTests.cs
tests/Processor.IntegrationTests/Consumers/NotificationConsumerTests.cs
tests/Processor.Tests/Consumers/CustomsDeclarationsConsumerTests.cs
tests/Processor.Tests/Consumers/NotificationConsumerTests.cs
tests/Processor.Tests/Models/FinalisationTests.Finalisation_ConversionToDataApiFinalisation_IsCorrect.verified.txt
tests/Processor.Tests/Models/FinalisationTests.cs
tests/TestFixtures/CustomsDeclarationFixtures.cs
tests/TestFixtures/FinalisationFixtures.cs
tests/TestFixtures/ImportNotificationFixtures.cs

This adds the Finalisation message ingestion, processing and sending to the Data Api.

CDMS-477: Add Finalisation ingestion and processing

---

src/Processor/Validation/CustomsDeclarations/ClearanceRequestValidator.cs
tests/Processor.Tests/Validation/CustomsDeclarations/ClearanceRequestValidatorTests.cs

This adds a number of Clearance Request validation rules.  More to come.

CDMS-476: Add more Clearance Request validation rules

---

compose.yml
compose/start-localstack.sh
src/Processor/appsettings.json
tests/Processor.IntegrationTests/TestBase/SqsTestBase.cs

Update to new queue name

---

src/Processor/Consumers/CustomsDeclarationsConsumer.cs
src/Processor/Models/CustomsDeclarations/ClearanceRequest.cs
src/Processor/Models/CustomsDeclarations/InboundError.cs
src/Processor/Processor.csproj
tests/Processor.Tests/Consumers/CustomsDeclarationsConsumerTests.cs
tests/Processor.Tests/Models/InboundErrorTests.InboundError_ConversionToDataApiInboundError_IsCorrect.verified.txt
tests/Processor.Tests/Models/InboundErrorTests.cs
tests/TestFixtures/CustomsDeclarationFixtures.cs
tests/TestFixtures/InboundErrorFixtures.cs

We will receive errors from CDS, we need to store them.

CDMS-482: Process and save Inbound Error notifications

---

src/Processor/Consumers/CustomsDeclarationsConsumer.cs
src/Processor/Models/CustomsDeclarations/InboundError.cs
src/Processor/Processor.csproj
tests/Processor.IntegrationTests/Consumers/CustomsDeclarationsConsumerTests.cs
tests/Processor.Tests/Consumers/CustomsDeclarationsConsumerTests.cs
tests/Processor.Tests/Models/InboundErrorTests.cs

We need to store when validation errors occur in the Data Api so the sender can be informed.

CDMS-476: Report validation errors to the Data Api

---

src/Processor/Consumers/NotificationConsumer.cs
src/Processor/Models/ImportNotification/ImportNotification.cs
tests/Processor.Tests/Consumers/NotificationConsumerTests.cs
tests/Processor.Tests/Models/ImportNotificationTests.ImportNotificationWithRiskAssessment_ConversionToDataApiImportPreNotification_IsCorrect.verified.txt
tests/Processor.Tests/Models/ImportNotificationTests.ImportNotificationWithRiskAssessment_DeserializedFromASB_IsCorrect.verified.txt
tests/Processor.Tests/Models/ImportNotificationTests.ImportNotification_ConversionToDataApiImportPreNotification_IsCorrect.verified.txt
tests/Processor.Tests/Models/ImportNotificationTests.ImportNotification_DeserializedFromASB_IsCorrect.verified.txt
tests/Processor.Tests/Models/ImportNotificationTests.cs
tests/TestFixtures/ImportNotificationFixtures.cs

The commodities were not being sent to the Data Api, meaning that the Beans were not stored.

BAU: Add Beans verify tests, fixing Commodity and Risk Assessments

---

src/Processor/Consumers/NotificationConsumer.cs
tests/Processor.Tests/Consumers/NotificationConsumerTests.cs

There is a potential that a notification that has a status of VALIDATED can come in microseconds after a notification is stored that is IN_PROGRESS. This currently results in the message being skipped.
This updates the logic to check whether the new notification is later in the lifecycle of a notification to aid in deciding whether to skip the message.

CDMS-649: Optimise logic around new notification validation

---

src/Processor/appsettings.cdp.test.json

Add data API endpoint base address for TEST with GMR topic name/subscription

---

compose.yml
src/Processor/Configuration/DataApiOptions.cs
src/Processor/Extensions/ServiceCollectionExtensions.cs
src/Processor/Health/DataApiHealthCheck.cs
src/Processor/Health/DataApiHealthCheckBuilderExtensions.cs
src/Processor/Health/ServiceCollectionExtensions.cs
src/Processor/Health/WebApplicationExtensions.cs
tests/Processor.IntegrationTests/Health/HealthTests.cs

Make use of PR https://github.com/DEFRA/trade-imports-data-api/pull/96 so we can check the processor is connected OK to the data API in each environment.

Add health check for data API

---

src/Processor/Validation/CustomsDeclarations/CommodityValidator.cs
tests/Processor.Tests/Validation/CustomsDeclarations/CommodityValidatorTests.cs

See ticket for explanation of why the validation is being disabled.

Temp disable of ALVSVAL317 validation

---

src/Processor/Models/ImportNotification/Mappers/CatchCertificateAttachmentMapper.cs
src/Processor/Models/ImportNotification/Mappers/LaboratoryTestsMapper.cs
tests/Processor.Tests/Validation/CustomsDeclarations/CheckValidatorTests.cs
tests/Processor.Tests/Validation/CustomsDeclarations/ClearanceRequestValidatorTests.cs
tests/Processor.Tests/Validation/CustomsDeclarations/CustomsDeclarationsMessageValidatorTests.cs
tests/Processor.Tests/Validation/CustomsDeclarations/ImportDocumentValidatorTests.cs

Address current sonar issues

---

src/Processor/Utils/Logging/WebApplicationBuilderExtensions.cs

I want to double check what is reported in CDP logs for a bad message, in case this logging filter is now hiding an error.

Temp change to include SMB errors

---

src/Processor/Utils/Logging/WebApplicationBuilderExtensions.cs

Reverts DEFRA/trade-imports-processor#150
Confirmed this was nothing to do with the problem I'm seeing.

Revert "Temp change to include SMB errors"

---

src/Processor/appsettings.cdp.prod.json

To make use of the relevant azure service bus topic subscriptions

CDMS-554 - Add production environment appsettings

---

src/Processor/Extensions/ServiceCollectionExtensions.cs

It turns out there is a bug within SMB where the AutoStartConsumers are not respected when using child buses: https://github.com/zarusz/SlimMessageBus/issues/414 
This PR changes the code not to register the child bus if the flag is set to false

Change how auto starts consumers are working

---

src/Processor/Extensions/ServiceCollectionExtensions.cs

These are not critical at the moment so removing for now.

Remove background service tasks that poll for dead letter counts (due to current size of dead letter queues)

---

src/Processor/Metrics/MetricsMiddleware.cs

Prevent the raw path from appearing in metrics as it might contain sensitive data

---

src/Processor/Consumers/CustomsDeclarationsConsumer.cs
src/Processor/Consumers/GmrsConsumer.cs
src/Processor/Consumers/NotificationConsumer.cs

Change logging output for format date time as ISO 8601.

CDMS-930: Change date time logging format
